[build]
target = "index.html"
dist = "dist"

[[hooks]]
stage = "build"
command = "sh"
command_arguments = ["-c", "if [[ ${TRUNK_PROFILE} == \"debug\" ]]; then tailwindcss -i src/tailwind.css -o $TRUNK_STAGING_DIR/tailwind.css; fi"]
