name: Continuous deployment
permissions:
  contents: write
on:
  workflow_run:
    branches: [main]
    workflows: [Rust_Build]
    types: [completed]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '14'
      - run: npm install -D tailwindcss

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      - uses: jetli/trunk-action@v0.1.0
      - uses: jetli/wasm-bindgen-action@v0.1.0

      - run: trunk build --release

      - run: awk -i inplace '{gsub(/\/homepage/,"./homepage");}1' dist/index.html && awk -i inplace '{gsub(/=\//,"=./");}1' dist/index.html #Maybe there's one command to do this, I don't care, it's small and fast anyway

      - run: echo www.wyatt.rs > CNAME

      - uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
